_Simple Hello world Python Program_


In [6]:
train_set = [
    [1, 0, 0, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0, 1, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 1, 0, 1, 0, 0, 0, 1],
    [0, 0, 1, 1, 0, 0, 1, 0, 1],
    [0, 0, 1, 1, 0, 0, 1, 1, 0],
    [0, 1, 0, 1, 0, 0, 1, 1, 1],
    [1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 0, 0, 1, 0, 1, 1, 1],
    [0, 1, 0, 0, 1, 0, 0, 1, 1],
    [0, 1, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 1, 0, 1, 0, 0, 1, 0]
]

14

In [11]:
import numpy as np

import math

def p(w, y, x):
    return 1 / (1 + math.exp(-y * np.dot(w, x)))

def train(train_set, alpha=0.01, max_iter=1000):
    w = np.zeros(8)
    for _ in range(max_iter):
        for x in train_set:
            y = x[-1]
            x = np.array(x[:-1])
            w += alpha * (1 - p(w, y, x)) * y * x
    return w


w = train(train_set=train_set)

x = [1, 0, 0, 0, 0, 1, 1, 0]

y = p(w, 1, x)
not_y = p(w, -1, x)

print(y, not_y)

print(y + not_y)

0.9853104240995146 0.014689575900485408
1.0


In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
row = A.sum(axis=1)
print(row)

[128.4 165.2 236.7]


In [4]:
cal = A.sum(axis=0)

print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100 * A / cal.reshape(1, 4)

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
