Numpy Arrays

In [5]:
import numpy as np

a = np.arange(15).reshape(3, 5)

print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64


In [13]:
print(a.sum(axis=0))
print(a.sum(axis=1))

a.sort(axis=0)
a.T

[15 18 21 24 27]
[10 35 60]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])