# Twice Model
> Just one perceptron to double numbers

In [54]:
import numpy as np
import matplotlib.pyplot as plt

train_set = np.array([[x, 2*x] for x in range(10)])
train_set

array([[ 0,  0],
       [ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10],
       [ 6, 12],
       [ 7, 14],
       [ 8, 16],
       [ 9, 18]])

In [55]:
np.random.seed(42)

w = np.random.rand(1) * 10
w

array([3.74540119])

In [56]:
def forward(x):
    return x * w

def lost(x, y, w):
    return (y - w * x)**2

def cost(w, train_set):
    cost = 0
    for x, y in train_set:
        cost += lost(x, y, w)
    return cost / len(train_set)

cost(w, train_set)

array([86.8231213])

In [57]:
def finite_difference(w, train_set, h=1e-10):
    return (cost(w + h, train_set) - cost(w, train_set)) / h

eps = 1e-10
finite_difference(w, train_set, h=eps)

array([99.48806223])

In [58]:
rate = 0.01
# np.random.seed(42)
w = np.random.rand(1) * 100
print(f"w = {w}, cost = {cost(w, train_set)}")

ws = []

EPOCHS = 16
for i in range(EPOCHS):
    ws.append(w)
    dw = finite_difference(w, train_set, h=eps)
    w -= rate * dw

print(f"w = {w}, cost = {cost(w, train_set)}")

w = [95.07143064], cost = [246875.29924449]
w = [2.00012716], cost = [4.60830604e-07]
